### ISSUE TITLE
Dark mode doesn't toggle in Fish edit and submit boxes

### ISSUE THREAD

**Issue by ColtonTurner** [WVU-CS330-2024-08-Group10/tackle-app#10]
Dark mode causes the text to change in the Fish edit and submit boxes, but the box does no go to dark mode, causing almost white text on a white background. The edit and submit boxes should change to be in dark mode instead of staying in light mode.

To recreate,

* Turn on dark mode
* Go to the personal Tab
* Press the "Edit" button or the "Submit New Catch!" button, then you will see that the text has changed but the box has not

Name: Colton Turner

**Comment by AnonUserGuy** [comment]
LukeDuke fixed this
