### ISSUE TITLE
Dark Mode Erasing Borders

### ISSUE THREAD

**Issue by Budwii3245** [WVU-CS330-2024-08-Group10/tackle-app#8]
Currently when dark mode is active the borders for elements do not change color. Elements on the "Home", "Weather", and "Personal" pages have black borders. So when dark mode is active the content in these elements is just floating with no borders. 

To recreate the issue 

- Turn on dark mode in the top right of the page
- Navigate to either "Home", "Weather", or "Personal"
- The borders will be gone (can check the difference by toggling between while on the page)

Name: Christian Williams

**Comment by AnonUserGuy** [comment]
LukeDuke fixed this
